# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class AddWorkflowChecklistPreset(BaseModel):
    add_workflow_checklist_preset: Optional[
        "AddWorkflowChecklistPresetAddWorkflowChecklistPreset"
    ] = Field(alias="addWorkflowChecklistPreset")


class AddWorkflowChecklistPresetAddWorkflowChecklistPreset(BaseModel):
    checklist_preset: Optional[
        "AddWorkflowChecklistPresetAddWorkflowChecklistPresetChecklistPreset"
    ] = Field(alias="checklistPreset")


class AddWorkflowChecklistPresetAddWorkflowChecklistPresetChecklistPreset(BaseModel):
    id: str
    content: str
    assigned_user: Optional[
        "AddWorkflowChecklistPresetAddWorkflowChecklistPresetChecklistPresetAssignedUser"
    ] = Field(alias="assignedUser")


class AddWorkflowChecklistPresetAddWorkflowChecklistPresetChecklistPresetAssignedUser(
    BaseModel
):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


AddWorkflowChecklistPreset.model_rebuild()
AddWorkflowChecklistPresetAddWorkflowChecklistPreset.model_rebuild()
AddWorkflowChecklistPresetAddWorkflowChecklistPresetChecklistPreset.model_rebuild()
