# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AssetStatusType, CopyrightStatus, TagSource


class Asset(BaseModel):
    asset: Optional["AssetAsset"]


class AssetAsset(BaseModel):
    typename__: Literal[
        "Asset", "Audio", "Document", "EmbeddedContent", "File", "Image", "Video"
    ] = Field(alias="__typename")
    id: str
    creator: "AssetAssetCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["AssetAssetModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    title: str
    description: Optional[str]
    attachments: Optional[List[Optional["AssetAssetAttachments"]]]
    external_id: Optional[str] = Field(alias="externalId")
    tags: Optional[List[Optional["AssetAssetTags"]]]
    copyright: Optional["AssetAssetCopyright"]
    expires_at: Optional[Any] = Field(alias="expiresAt")
    licenses: Optional[List[Optional["AssetAssetLicenses"]]]
    status: AssetStatusType
    related_assets: "AssetAssetRelatedAssets" = Field(alias="relatedAssets")
    comments: Optional["AssetAssetComments"]
    current_user_permissions: "AssetAssetCurrentUserPermissions" = Field(
        alias="currentUserPermissions"
    )


class AssetAssetCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    email: Any
    name: Optional[str]
    avatar: Optional[Any]


class AssetAssetModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    email: Any
    name: Optional[str]
    avatar: Optional[Any]


class AssetAssetAttachments(BaseModel):
    id: str
    creator: "AssetAssetAttachmentsCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["AssetAssetAttachmentsModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    name: Optional[str]
    filename: Optional[str]
    type: Optional[str]
    external_id: Optional[str] = Field(alias="externalId")
    extension: Optional[str]
    size: Optional[Any]
    download_url: Optional[Any] = Field(alias="downloadUrl")


class AssetAssetAttachmentsCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    email: Any
    name: Optional[str]
    avatar: Optional[Any]


class AssetAssetAttachmentsModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    email: Any
    name: Optional[str]
    avatar: Optional[Any]


class AssetAssetTags(BaseModel):
    value: str
    source: Optional[TagSource]


class AssetAssetCopyright(BaseModel):
    status: CopyrightStatus
    notice: Optional[str]


class AssetAssetLicenses(BaseModel):
    id: str
    title: str
    license: str
    add_by_default: bool = Field(alias="addByDefault")
    require_consensus: bool = Field(alias="requireConsensus")


class AssetAssetRelatedAssets(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[List[Optional["AssetAssetRelatedAssetsItems"]]]


class AssetAssetRelatedAssetsItems(BaseModel):
    typename__: Literal[
        "Asset", "Audio", "Document", "EmbeddedContent", "File", "Image", "Video"
    ] = Field(alias="__typename")
    id: str
    creator: "AssetAssetRelatedAssetsItemsCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["AssetAssetRelatedAssetsItemsModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    title: str
    description: Optional[str]
    attachments: Optional[List[Optional["AssetAssetRelatedAssetsItemsAttachments"]]]
    external_id: Optional[str] = Field(alias="externalId")
    tags: Optional[List[Optional["AssetAssetRelatedAssetsItemsTags"]]]
    copyright: Optional["AssetAssetRelatedAssetsItemsCopyright"]
    expires_at: Optional[Any] = Field(alias="expiresAt")
    licenses: Optional[List[Optional["AssetAssetRelatedAssetsItemsLicenses"]]]
    status: AssetStatusType
    related_assets: "AssetAssetRelatedAssetsItemsRelatedAssets" = Field(
        alias="relatedAssets"
    )
    comments: Optional["AssetAssetRelatedAssetsItemsComments"]
    current_user_permissions: "AssetAssetRelatedAssetsItemsCurrentUserPermissions" = (
        Field(alias="currentUserPermissions")
    )
    custom_metadata: List["AssetAssetRelatedAssetsItemsCustomMetadata"] = Field(
        alias="customMetadata"
    )
    location: "AssetAssetRelatedAssetsItemsLocation"


class AssetAssetRelatedAssetsItemsCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    email: Any
    name: Optional[str]
    avatar: Optional[Any]


class AssetAssetRelatedAssetsItemsModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    email: Any
    name: Optional[str]
    avatar: Optional[Any]


class AssetAssetRelatedAssetsItemsAttachments(BaseModel):
    id: str
    created_at: Any = Field(alias="createdAt")
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    name: Optional[str]
    filename: Optional[str]
    type: Optional[str]
    external_id: Optional[str] = Field(alias="externalId")
    extension: Optional[str]
    size: Optional[Any]
    download_url: Optional[Any] = Field(alias="downloadUrl")


class AssetAssetRelatedAssetsItemsTags(BaseModel):
    value: str
    source: Optional[TagSource]


class AssetAssetRelatedAssetsItemsCopyright(BaseModel):
    status: CopyrightStatus
    notice: Optional[str]


class AssetAssetRelatedAssetsItemsLicenses(BaseModel):
    id: str
    title: str
    license: str
    add_by_default: bool = Field(alias="addByDefault")
    require_consensus: bool = Field(alias="requireConsensus")


class AssetAssetRelatedAssetsItemsRelatedAssets(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class AssetAssetRelatedAssetsItemsComments(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[List[Optional["AssetAssetRelatedAssetsItemsCommentsItems"]]]


class AssetAssetRelatedAssetsItemsCommentsItems(BaseModel):
    id: str
    created_at: Any = Field(alias="createdAt")
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    content: str
    is_resolved: bool = Field(alias="isResolved")


class AssetAssetRelatedAssetsItemsCurrentUserPermissions(BaseModel):
    can_edit: bool = Field(alias="canEdit")
    can_delete: bool = Field(alias="canDelete")
    can_download: bool = Field(alias="canDownload")
    can_comment: bool = Field(alias="canComment")


class AssetAssetRelatedAssetsItemsCustomMetadata(BaseModel):
    typename__: Literal[
        "CustomMetadata", "CustomMetadataValue", "CustomMetadataValues"
    ] = Field(alias="__typename")
    property: "AssetAssetRelatedAssetsItemsCustomMetadataProperty"


class AssetAssetRelatedAssetsItemsCustomMetadataProperty(BaseModel):
    id: str
    created_at: Any = Field(alias="createdAt")
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    name: str
    help_text: Optional[str] = Field(alias="helpText")
    is_required: bool = Field(alias="isRequired")
    default_value: Optional[Any] = Field(alias="defaultValue")


class AssetAssetRelatedAssetsItemsLocation(BaseModel):
    brand: Optional["AssetAssetRelatedAssetsItemsLocationBrand"]
    library: Optional["AssetAssetRelatedAssetsItemsLocationLibrary"]
    workspace_project: Optional[
        "AssetAssetRelatedAssetsItemsLocationWorkspaceProject"
    ] = Field(alias="workspaceProject")
    folder: Optional["AssetAssetRelatedAssetsItemsLocationFolder"]


class AssetAssetRelatedAssetsItemsLocationBrand(BaseModel):
    id: str
    name: str


class AssetAssetRelatedAssetsItemsLocationLibrary(BaseModel):
    id: str
    name: Optional[str]


class AssetAssetRelatedAssetsItemsLocationWorkspaceProject(BaseModel):
    id: str
    name: Optional[str]


class AssetAssetRelatedAssetsItemsLocationFolder(BaseModel):
    id: str
    name: str


class AssetAssetComments(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class AssetAssetCurrentUserPermissions(BaseModel):
    can_edit: bool = Field(alias="canEdit")
    can_delete: bool = Field(alias="canDelete")
    can_download: bool = Field(alias="canDownload")
    can_comment: bool = Field(alias="canComment")


Asset.model_rebuild()
AssetAsset.model_rebuild()
AssetAssetAttachments.model_rebuild()
AssetAssetRelatedAssets.model_rebuild()
AssetAssetRelatedAssetsItems.model_rebuild()
AssetAssetRelatedAssetsItemsComments.model_rebuild()
AssetAssetRelatedAssetsItemsCustomMetadata.model_rebuild()
AssetAssetRelatedAssetsItemsLocation.model_rebuild()
