# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateLicense(BaseModel):
    create_license: Optional["CreateLicenseCreateLicense"] = Field(
        alias="createLicense"
    )


class CreateLicenseCreateLicense(BaseModel):
    license: "CreateLicenseCreateLicenseLicense"


class CreateLicenseCreateLicenseLicense(BaseModel):
    id: str
    title: str
    license: str
    add_by_default: bool = Field(alias="addByDefault")
    require_consensus: bool = Field(alias="requireConsensus")


CreateLicense.model_rebuild()
CreateLicenseCreateLicense.model_rebuild()
