# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreatePermissionToken(BaseModel):
    create_permission_token: Optional["CreatePermissionTokenCreatePermissionToken"] = (
        Field(alias="createPermissionToken")
    )


class CreatePermissionTokenCreatePermissionToken(BaseModel):
    permission_token: str = Field(alias="permissionToken")


CreatePermissionToken.model_rebuild()
