# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateAttachment(BaseModel):
    create_attachment: Optional["CreateAttachmentCreateAttachment"] = Field(
        alias="createAttachment"
    )


class CreateAttachmentCreateAttachment(BaseModel):
    job: "CreateAttachmentCreateAttachmentJob"


class CreateAttachmentCreateAttachmentJob(BaseModel):
    attachment_id: str = Field(alias="attachmentId")


CreateAttachment.model_rebuild()
CreateAttachmentCreateAttachment.model_rebuild()
