# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateAssetComment(BaseModel):
    create_asset_comment: Optional["CreateAssetCommentCreateAssetComment"] = Field(
        alias="createAssetComment"
    )


class CreateAssetCommentCreateAssetComment(BaseModel):
    comment: "CreateAssetCommentCreateAssetCommentComment"


class CreateAssetCommentCreateAssetCommentComment(BaseModel):
    id: str
    creator: "CreateAssetCommentCreateAssetCommentCommentCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["CreateAssetCommentCreateAssetCommentCommentModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    content: str
    mentioned_users: List[
        Optional["CreateAssetCommentCreateAssetCommentCommentMentionedUsers"]
    ] = Field(alias="mentionedUsers")
    is_resolved: bool = Field(alias="isResolved")
    replies: "CreateAssetCommentCreateAssetCommentCommentReplies"
    marking: Optional["CreateAssetCommentCreateAssetCommentCommentMarking"]
    current_user_permissions: (
        "CreateAssetCommentCreateAssetCommentCommentCurrentUserPermissions"
    ) = Field(alias="currentUserPermissions")


class CreateAssetCommentCreateAssetCommentCommentCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class CreateAssetCommentCreateAssetCommentCommentModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class CreateAssetCommentCreateAssetCommentCommentMentionedUsers(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class CreateAssetCommentCreateAssetCommentCommentReplies(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[
        List[Optional["CreateAssetCommentCreateAssetCommentCommentRepliesItems"]]
    ]


class CreateAssetCommentCreateAssetCommentCommentRepliesItems(BaseModel):
    id: str
    creator: "CreateAssetCommentCreateAssetCommentCommentRepliesItemsCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional[
        "CreateAssetCommentCreateAssetCommentCommentRepliesItemsModifier"
    ]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    content: str
    mentioned_users: List[
        Optional[
            "CreateAssetCommentCreateAssetCommentCommentRepliesItemsMentionedUsers"
        ]
    ] = Field(alias="mentionedUsers")


class CreateAssetCommentCreateAssetCommentCommentRepliesItemsCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class CreateAssetCommentCreateAssetCommentCommentRepliesItemsModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class CreateAssetCommentCreateAssetCommentCommentRepliesItemsMentionedUsers(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class CreateAssetCommentCreateAssetCommentCommentMarking(BaseModel):
    typename__: Literal[
        "Marking", "MultiPageMarking", "SimpleMarking", "VideoMarking"
    ] = Field(alias="__typename")
    position: "CreateAssetCommentCreateAssetCommentCommentMarkingPosition"
    dimensions: Optional["CreateAssetCommentCreateAssetCommentCommentMarkingDimensions"]


class CreateAssetCommentCreateAssetCommentCommentMarkingPosition(BaseModel):
    x: Any
    y: Any


class CreateAssetCommentCreateAssetCommentCommentMarkingDimensions(BaseModel):
    width: Optional[Any]
    height: Optional[Any]


class CreateAssetCommentCreateAssetCommentCommentCurrentUserPermissions(BaseModel):
    can_edit: bool = Field(alias="canEdit")
    can_delete: bool = Field(alias="canDelete")
    can_reply: bool = Field(alias="canReply")


CreateAssetComment.model_rebuild()
CreateAssetCommentCreateAssetComment.model_rebuild()
CreateAssetCommentCreateAssetCommentComment.model_rebuild()
CreateAssetCommentCreateAssetCommentCommentReplies.model_rebuild()
CreateAssetCommentCreateAssetCommentCommentRepliesItems.model_rebuild()
CreateAssetCommentCreateAssetCommentCommentMarking.model_rebuild()
