# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateAssetVariant(BaseModel):
    create_asset_variant: Optional["CreateAssetVariantCreateAssetVariant"] = Field(
        alias="createAssetVariant"
    )


class CreateAssetVariantCreateAssetVariant(BaseModel):
    job: "CreateAssetVariantCreateAssetVariantJob"


class CreateAssetVariantCreateAssetVariantJob(BaseModel):
    variant_id: str = Field(alias="variantId")


CreateAssetVariant.model_rebuild()
CreateAssetVariantCreateAssetVariant.model_rebuild()
