# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateAccountUser(BaseModel):
    create_account_user: Optional["CreateAccountUserCreateAccountUser"] = Field(
        alias="createAccountUser"
    )


class CreateAccountUserCreateAccountUser(BaseModel):
    account_user: Optional["CreateAccountUserCreateAccountUserAccountUser"] = Field(
        alias="accountUser"
    )


class CreateAccountUserCreateAccountUserAccountUser(BaseModel):
    id: str
    email: Any
    name: Optional[str]
    avatar: Optional[Any]


CreateAccountUser.model_rebuild()
CreateAccountUserCreateAccountUser.model_rebuild()
