# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class CurrentUser(BaseModel):
    current_user: "CurrentUserCurrentUser" = Field(alias="currentUser")


class CurrentUserCurrentUser(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


CurrentUser.model_rebuild()
