# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteBrand(BaseModel):
    delete_brand: Optional["DeleteBrandDeleteBrand"] = Field(alias="deleteBrand")


class DeleteBrandDeleteBrand(BaseModel):
    id: str


DeleteBrand.model_rebuild()
