# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteAccountUser(BaseModel):
    delete_account_user: Optional["DeleteAccountUserDeleteAccountUser"] = Field(
        alias="deleteAccountUser"
    )


class DeleteAccountUserDeleteAccountUser(BaseModel):
    id: Optional[str]


DeleteAccountUser.model_rebuild()
