# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteWorkflowTask(BaseModel):
    delete_workflow_task: Optional["DeleteWorkflowTaskDeleteWorkflowTask"] = Field(
        alias="deleteWorkflowTask"
    )


class DeleteWorkflowTaskDeleteWorkflowTask(BaseModel):
    id: str


DeleteWorkflowTask.model_rebuild()
