# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteLicense(BaseModel):
    delete_license: Optional["DeleteLicenseDeleteLicense"] = Field(
        alias="deleteLicense"
    )


class DeleteLicenseDeleteLicense(BaseModel):
    id: str


DeleteLicense.model_rebuild()
