# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteCustomMetadataProperty(BaseModel):
    delete_custom_metadata_property: Optional[
        "DeleteCustomMetadataPropertyDeleteCustomMetadataProperty"
    ] = Field(alias="deleteCustomMetadataProperty")


class DeleteCustomMetadataPropertyDeleteCustomMetadataProperty(BaseModel):
    id: str


DeleteCustomMetadataProperty.model_rebuild()
