# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteAttachment(BaseModel):
    delete_attachment: Optional["DeleteAttachmentDeleteAttachment"] = Field(
        alias="deleteAttachment"
    )


class DeleteAttachmentDeleteAttachment(BaseModel):
    id: str


DeleteAttachment.model_rebuild()
