# Generated by ariadne-codegen
# Source: public-beta.graphql

from enum import Enum


class TagSource(str, Enum):
    MANUAL = "MANUAL"
    AUTO = "AUTO"


class CopyrightStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    COPYRIGHTED = "COPYRIGHTED"
    PUBLIC = "PUBLIC"


class AssetStatusType(str, Enum):
    FINISHED = "FINISHED"
    PROCESSING = "PROCESSING"
    PROCESSING_FAILED = "PROCESSING_FAILED"


class AssetCommentStatusFilter(str, Enum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    ALL = "ALL"


class WorkflowStatusEnterRule(str, Enum):
    TASK_REQUIRES_ASSIGNEE = "TASK_REQUIRES_ASSIGNEE"
    TASK_REQUIRES_MESSAGE = "TASK_REQUIRES_MESSAGE"


class AssetQueryFilterSortType(str, Enum):
    RELEVANCE = "RELEVANCE"
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"
    TITLE_ASCENDING = "TITLE_ASCENDING"
    TITLE_DESCENDING = "TITLE_DESCENDING"


class ConditionType(str, Enum):
    METADATA_VALUE = "METADATA_VALUE"
    CUSTOM_METADATA_VALUE = "CUSTOM_METADATA_VALUE"
    EXTERNAL_ID = "EXTERNAL_ID"
    TAG = "TAG"
    FILE_EXTENSION = "FILE_EXTENSION"


class ConditionOperator(str, Enum):
    IS = "IS"
    IS_NOT = "IS_NOT"


class AssetType(str, Enum):
    AUDIO = "AUDIO"
    DOCUMENT = "DOCUMENT"
    FILE = "FILE"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"


class AccountQuerySortByInput(str, Enum):
    RELEVANCE = "RELEVANCE"
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"


class AccountQuerySourceTypeInput(str, Enum):
    LIBRARIES = "LIBRARIES"
    WORKSPACE_PROJECTS = "WORKSPACE_PROJECTS"
    LIBRARY_PAGES = "LIBRARY_PAGES"


class ProjectType(str, Enum):
    DOCUMENT_LIBRARY = "DOCUMENT_LIBRARY"
    ICON_LIBRARY = "ICON_LIBRARY"
    LOGO_LIBRARY = "LOGO_LIBRARY"
    MEDIA_LIBRARY = "MEDIA_LIBRARY"
    WORKSPACE = "WORKSPACE"


class BrandQuerySortByInput(str, Enum):
    RELEVANCE = "RELEVANCE"
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"


class BrandSearchQuerySource(str, Enum):
    LIBRARIES = "LIBRARIES"
    WORKSPACE_PROJECTS = "WORKSPACE_PROJECTS"
    EVERYWHERE = "EVERYWHERE"
    LIBRARY_VIEWS = "LIBRARY_VIEWS"


class BrandQuerySourceTypeInput(str, Enum):
    LIBRARIES = "LIBRARIES"
    WORKSPACE_PROJECTS = "WORKSPACE_PROJECTS"
    LIBRARY_PAGES = "LIBRARY_PAGES"


class LibraryQuerySort(str, Enum):
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"


class WorkspaceProjectStateFilter(str, Enum):
    ALL = "ALL"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class WorkspaceProjectQuerySort(str, Enum):
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"
    NEWEST_ACTIVITY = "NEWEST_ACTIVITY"
    OLDEST_ACTIVITY = "OLDEST_ACTIVITY"


class LanguageCode(str, Enum):
    AB = "AB"
    AA = "AA"
    AF = "AF"
    AK = "AK"
    SQ = "SQ"
    AM = "AM"
    AR = "AR"
    AN = "AN"
    HY = "HY"
    AS = "AS"
    AV = "AV"
    AE = "AE"
    AY = "AY"
    AZ = "AZ"
    BM = "BM"
    BA = "BA"
    EU = "EU"
    BE = "BE"
    BN = "BN"
    BH = "BH"
    BI = "BI"
    BS = "BS"
    BR = "BR"
    BG = "BG"
    MY = "MY"
    CA = "CA"
    KM = "KM"
    CH = "CH"
    CE = "CE"
    NY = "NY"
    ZH = "ZH"
    CU = "CU"
    CV = "CV"
    KW = "KW"
    CO = "CO"
    CR = "CR"
    HR = "HR"
    CS = "CS"
    DA = "DA"
    DV = "DV"
    NL = "NL"
    DZ = "DZ"
    EN = "EN"
    EO = "EO"
    ET = "ET"
    EE = "EE"
    FO = "FO"
    FJ = "FJ"
    FI = "FI"
    FR = "FR"
    FF = "FF"
    GD = "GD"
    GL = "GL"
    LG = "LG"
    KA = "KA"
    DE = "DE"
    KI = "KI"
    EL = "EL"
    KL = "KL"
    GN = "GN"
    GU = "GU"
    HT = "HT"
    HA = "HA"
    HE = "HE"
    HZ = "HZ"
    HI = "HI"
    HO = "HO"
    HU = "HU"
    IS = "IS"
    IO = "IO"
    IG = "IG"
    ID = "ID"
    IA = "IA"
    IE = "IE"
    IU = "IU"
    IK = "IK"
    GA = "GA"
    IT = "IT"
    JA = "JA"
    JV = "JV"
    KN = "KN"
    KR = "KR"
    KS = "KS"
    KK = "KK"
    RW = "RW"
    KV = "KV"
    KG = "KG"
    KO = "KO"
    KJ = "KJ"
    KU = "KU"
    KY = "KY"
    LO = "LO"
    LA = "LA"
    LV = "LV"
    LB = "LB"
    LI = "LI"
    LN = "LN"
    LT = "LT"
    LU = "LU"
    MK = "MK"
    MG = "MG"
    MS = "MS"
    ML = "ML"
    MT = "MT"
    GV = "GV"
    MI = "MI"
    MR = "MR"
    MH = "MH"
    RO = "RO"
    MN = "MN"
    NA = "NA"
    NV = "NV"
    ND = "ND"
    NG = "NG"
    NE = "NE"
    SE = "SE"
    NO = "NO"
    NB = "NB"
    NN = "NN"
    II = "II"
    OC = "OC"
    OJ = "OJ"
    OR = "OR"
    OM = "OM"
    OS = "OS"
    PI = "PI"
    PA = "PA"
    PS = "PS"
    FA = "FA"
    PL = "PL"
    PT = "PT"
    QU = "QU"
    RM = "RM"
    RN = "RN"
    RU = "RU"
    SM = "SM"
    SG = "SG"
    SA = "SA"
    SC = "SC"
    SR = "SR"
    SN = "SN"
    SD = "SD"
    SI = "SI"
    SK = "SK"
    SL = "SL"
    SO = "SO"
    ST = "ST"
    NR = "NR"
    ES = "ES"
    SU = "SU"
    SW = "SW"
    SS = "SS"
    SV = "SV"
    TL = "TL"
    TY = "TY"
    TG = "TG"
    TA = "TA"
    TT = "TT"
    TE = "TE"
    TH = "TH"
    BO = "BO"
    TI = "TI"
    TO = "TO"
    TS = "TS"
    TN = "TN"
    TR = "TR"
    TK = "TK"
    TW = "TW"
    UG = "UG"
    UK = "UK"
    UR = "UR"
    UZ = "UZ"
    VE = "VE"
    VI = "VI"
    VO = "VO"
    WA = "WA"
    CY = "CY"
    FY = "FY"
    WO = "WO"
    XH = "XH"
    YI = "YI"
    YO = "YO"
    ZA = "ZA"
    ZU = "ZU"


class LibraryType(str, Enum):
    ICON_LIBRARY = "ICON_LIBRARY"
    MEDIA_LIBRARY = "MEDIA_LIBRARY"
    LOGO_LIBRARY = "LOGO_LIBRARY"
    DOCUMENT_LIBRARY = "DOCUMENT_LIBRARY"


class CreativeTemplateQuerySort(str, Enum):
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"


class CreativeTemplateVariableType(str, Enum):
    BOOL = "BOOL"
    NUMBER = "NUMBER"
    TEXT = "TEXT"
    IMAGE = "IMAGE"
    COLOR = "COLOR"


class CreativeJobStatus(str, Enum):
    PROCESSING = "PROCESSING"
    RENDERING = "RENDERING"
    CANCELED = "CANCELED"
    FINISHED = "FINISHED"
    FAILED = "FAILED"


class CustomMetadataPropertyTypeName(str, Enum):
    SELECT = "SELECT"
    MULTISELECT = "MULTISELECT"
    TEXT = "TEXT"
    LONGTEXT = "LONGTEXT"
    DATE = "DATE"
    NUMBER = "NUMBER"
    URL = "URL"


class CustomMetadataPropertyPositionPlacement(str, Enum):
    FIRST = "FIRST"
    LAST = "LAST"
    BEFORE = "BEFORE"
    AFTER = "AFTER"


class MetadataFieldType(str, Enum):
    SELECT = "SELECT"
    TEXT = "TEXT"
    LONGTEXT = "LONGTEXT"
    DATE = "DATE"
    NUMBER = "NUMBER"


class ProjectPermission(str, Enum):
    EDIT = "EDIT"
    COMMENT = "COMMENT"
    VIEW = "VIEW"
    ADMIN = "ADMIN"
    TRANSLATE = "TRANSLATE"


class CreativeExportFormat(str, Enum):
    PNG = "PNG"
    JPG = "JPG"
    PDF = "PDF"


class CreativeExportQuality(str, Enum):
    MAXIMUM = "MAXIMUM"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
