# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GuidelinePage(BaseModel):
    guideline_page: Optional["GuidelinePageGuidelinePage"] = Field(
        alias="guidelinePage"
    )


class GuidelinePageGuidelinePage(BaseModel):
    id: str
    title: str
    url: Any
    sections: Optional["GuidelinePageGuidelinePageSections"]


class GuidelinePageGuidelinePageSections(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[List[Optional["GuidelinePageGuidelinePageSectionsItems"]]]


class GuidelinePageGuidelinePageSectionsItems(BaseModel):
    id: str
    elements: Optional["GuidelinePageGuidelinePageSectionsItemsElements"]


class GuidelinePageGuidelinePageSectionsItemsElements(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[
        List[
            Optional[
                Annotated[
                    Union[
                        "GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageHeading",
                        "GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageBlock",
                        "GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageBlockReference",
                    ],
                    Field(discriminator="typename__"),
                ]
            ]
        ]
    ]


class GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageHeading(
    BaseModel
):
    typename__: Literal["GuidelinePageHeading"] = Field(alias="__typename")
    id: str
    title: str
    last_modified: Any = Field(alias="lastModified")


class GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageBlock(BaseModel):
    typename__: Literal["GuidelinePageBlock"] = Field(alias="__typename")
    id: str
    content: Optional[str]
    url: Any
    last_modified: Any = Field(alias="lastModified")


class GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageBlockReference(
    BaseModel
):
    typename__: Literal["GuidelinePageBlockReference"] = Field(alias="__typename")
    id: str
    block: "GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageBlockReferenceBlock"


class GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageBlockReferenceBlock(
    BaseModel
):
    id: str
    content: Optional[str]
    url: Any
    last_modified: Any = Field(alias="lastModified")


GuidelinePage.model_rebuild()
GuidelinePageGuidelinePage.model_rebuild()
GuidelinePageGuidelinePageSections.model_rebuild()
GuidelinePageGuidelinePageSectionsItems.model_rebuild()
GuidelinePageGuidelinePageSectionsItemsElements.model_rebuild()
GuidelinePageGuidelinePageSectionsItemsElementsItemsGuidelinePageBlockReference.model_rebuild()
