# Generated by ariadne-codegen
# Source: queries-mutations

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class MoveFolders(BaseModel):
    move_folders: Optional["MoveFoldersMoveFolders"] = Field(alias="moveFolders")


class MoveFoldersMoveFolders(BaseModel):
    ids: Optional[List[str]]


MoveFolders.model_rebuild()
