# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class Node(BaseModel):
    node: Optional["NodeNode"]


class NodeNode(BaseModel):
    typename__: Literal[
        "Account",
        "AccountUser",
        "AssetAttachment",
        "AssetComment",
        "Audio",
        "Brand",
        "Collection",
        "CustomMetadataProperty",
        "Document",
        "DocumentLibrary",
        "EmbeddedContent",
        "File",
        "Guideline",
        "IconLibrary",
        "Image",
        "LibraryPage",
        "LibraryPageCollection",
        "LogoLibrary",
        "MediaLibrary",
        "Node",
        "ProjectWebhook",
        "SubFolder",
        "UserGroup",
        "Video",
        "Workspace",
    ] = Field(alias="__typename")
    id: str


Node.model_rebuild()
