# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class RemoveWorkflowChecklistPreset(BaseModel):
    remove_workflow_checklist_preset: Optional[
        "RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPreset"
    ] = Field(alias="removeWorkflowChecklistPreset")


class RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPreset(BaseModel):
    checklist_preset: Optional[
        "RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPresetChecklistPreset"
    ] = Field(alias="checklistPreset")


class RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPresetChecklistPreset(
    BaseModel
):
    id: str
    content: str
    assigned_user: Optional[
        "RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPresetChecklistPresetAssignedUser"
    ] = Field(alias="assignedUser")


class RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPresetChecklistPresetAssignedUser(
    BaseModel
):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


RemoveWorkflowChecklistPreset.model_rebuild()
RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPreset.model_rebuild()
RemoveWorkflowChecklistPresetRemoveWorkflowChecklistPresetChecklistPreset.model_rebuild()
