# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ReplaceExternalDataSourceFile(BaseModel):
    replace_external_data_source_file: Optional[
        "ReplaceExternalDataSourceFileReplaceExternalDataSourceFile"
    ] = Field(alias="replaceExternalDataSourceFile")


class ReplaceExternalDataSourceFileReplaceExternalDataSourceFile(BaseModel):
    external_data_source_id: str = Field(alias="externalDataSourceId")


ReplaceExternalDataSourceFile.model_rebuild()
