# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ReplaceAsset(BaseModel):
    replace_asset: Optional["ReplaceAssetReplaceAsset"] = Field(alias="replaceAsset")


class ReplaceAssetReplaceAsset(BaseModel):
    job: "ReplaceAssetReplaceAssetJob"


class ReplaceAssetReplaceAssetJob(BaseModel):
    asset_id: str = Field(alias="assetId")


ReplaceAsset.model_rebuild()
ReplaceAssetReplaceAsset.model_rebuild()
