# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ReplaceAssetVariant(BaseModel):
    replace_asset_variant: Optional["ReplaceAssetVariantReplaceAssetVariant"] = Field(
        alias="replaceAssetVariant"
    )


class ReplaceAssetVariantReplaceAssetVariant(BaseModel):
    job: "ReplaceAssetVariantReplaceAssetVariantJob"


class ReplaceAssetVariantReplaceAssetVariantJob(BaseModel):
    variant_id: str = Field(alias="variantId")


ReplaceAssetVariant.model_rebuild()
ReplaceAssetVariantReplaceAssetVariant.model_rebuild()
