# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AssetStatusType, CopyrightStatus, TagSource, WorkflowStatusEnterRule


class SyncAssetTags(BaseModel):
    sync_asset_tags: Optional["SyncAssetTagsSyncAssetTags"] = Field(
        alias="syncAssetTags"
    )


class SyncAssetTagsSyncAssetTags(BaseModel):
    asset: Optional["SyncAssetTagsSyncAssetTagsAsset"]


class SyncAssetTagsSyncAssetTagsAsset(BaseModel):
    typename__: Literal[
        "Asset", "Audio", "Document", "EmbeddedContent", "File", "Image", "Video"
    ] = Field(alias="__typename")
    id: str
    creator: "SyncAssetTagsSyncAssetTagsAssetCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["SyncAssetTagsSyncAssetTagsAssetModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    title: str
    description: Optional[str]
    attachments: Optional[List[Optional["SyncAssetTagsSyncAssetTagsAssetAttachments"]]]
    external_id: Optional[str] = Field(alias="externalId")
    tags: Optional[List[Optional["SyncAssetTagsSyncAssetTagsAssetTags"]]]
    copyright: Optional["SyncAssetTagsSyncAssetTagsAssetCopyright"]
    availability: "SyncAssetTagsSyncAssetTagsAssetAvailability"
    expires_at: Optional[Any] = Field(alias="expiresAt")
    licenses: Optional[List[Optional["SyncAssetTagsSyncAssetTagsAssetLicenses"]]]
    status: AssetStatusType
    related_assets: "SyncAssetTagsSyncAssetTagsAssetRelatedAssets" = Field(
        alias="relatedAssets"
    )
    comments: Optional["SyncAssetTagsSyncAssetTagsAssetComments"]
    current_user_permissions: (
        "SyncAssetTagsSyncAssetTagsAssetCurrentUserPermissions"
    ) = Field(alias="currentUserPermissions")
    custom_metadata: List["SyncAssetTagsSyncAssetTagsAssetCustomMetadata"] = Field(
        alias="customMetadata"
    )
    workflow_task: Optional["SyncAssetTagsSyncAssetTagsAssetWorkflowTask"] = Field(
        alias="workflowTask"
    )


class SyncAssetTagsSyncAssetTagsAssetCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetAttachments(BaseModel):
    id: str
    creator: "SyncAssetTagsSyncAssetTagsAssetAttachmentsCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["SyncAssetTagsSyncAssetTagsAssetAttachmentsModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    name: Optional[str]
    filename: Optional[str]
    type: Optional[str]
    external_id: Optional[str] = Field(alias="externalId")
    extension: Optional[str]
    size: Optional[Any]
    download_url: Optional[Any] = Field(alias="downloadUrl")


class SyncAssetTagsSyncAssetTagsAssetAttachmentsCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetAttachmentsModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetTags(BaseModel):
    value: str
    source: Optional[TagSource]


class SyncAssetTagsSyncAssetTagsAssetCopyright(BaseModel):
    status: CopyrightStatus
    notice: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetAvailability(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class SyncAssetTagsSyncAssetTagsAssetLicenses(BaseModel):
    id: str
    title: str
    license: str
    add_by_default: bool = Field(alias="addByDefault")
    require_consensus: bool = Field(alias="requireConsensus")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssets(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[List[Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItems"]]]


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItems(BaseModel):
    typename__: Literal[
        "Asset", "Audio", "Document", "EmbeddedContent", "File", "Image", "Video"
    ] = Field(alias="__typename")
    id: str
    creator: "SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    title: str
    description: Optional[str]
    attachments: Optional[
        List[Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsAttachments"]]
    ]
    external_id: Optional[str] = Field(alias="externalId")
    tags: Optional[
        List[Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsTags"]]
    ]
    copyright: Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsCopyright"]
    availability: "SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsAvailability"
    expires_at: Optional[Any] = Field(alias="expiresAt")
    licenses: Optional[
        List[Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsLicenses"]]
    ]
    status: AssetStatusType
    related_assets: "SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsRelatedAssets" = (
        Field(alias="relatedAssets")
    )
    comments: Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsComments"]
    current_user_permissions: (
        "SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsCurrentUserPermissions"
    ) = Field(alias="currentUserPermissions")
    workflow_task: Optional[
        "SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsWorkflowTask"
    ] = Field(alias="workflowTask")
    variants: Optional["SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsVariants"]
    preview_background_color: Optional[
        "SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsPreviewBackgroundColor"
    ] = Field(alias="previewBackgroundColor")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsAttachments(BaseModel):
    id: str
    created_at: Any = Field(alias="createdAt")
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    name: Optional[str]
    filename: Optional[str]
    type: Optional[str]
    external_id: Optional[str] = Field(alias="externalId")
    extension: Optional[str]
    size: Optional[Any]
    download_url: Optional[Any] = Field(alias="downloadUrl")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsTags(BaseModel):
    value: str
    source: Optional[TagSource]


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsCopyright(BaseModel):
    status: CopyrightStatus
    notice: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsAvailability(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsLicenses(BaseModel):
    id: str
    title: str
    license: str
    add_by_default: bool = Field(alias="addByDefault")
    require_consensus: bool = Field(alias="requireConsensus")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsRelatedAssets(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsComments(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsCurrentUserPermissions(
    BaseModel
):
    can_edit: bool = Field(alias="canEdit")
    can_delete: bool = Field(alias="canDelete")
    can_download: bool = Field(alias="canDownload")
    can_comment: bool = Field(alias="canComment")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsWorkflowTask(BaseModel):
    id: str
    title: Optional[str]
    description: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsVariants(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItemsPreviewBackgroundColor(
    BaseModel
):
    red: Any
    green: Any
    blue: Any
    alpha: Any


class SyncAssetTagsSyncAssetTagsAssetComments(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[List[Optional["SyncAssetTagsSyncAssetTagsAssetCommentsItems"]]]


class SyncAssetTagsSyncAssetTagsAssetCommentsItems(BaseModel):
    id: str
    created_at: Any = Field(alias="createdAt")
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    content: str
    mentioned_users: List[
        Optional["SyncAssetTagsSyncAssetTagsAssetCommentsItemsMentionedUsers"]
    ] = Field(alias="mentionedUsers")
    is_resolved: bool = Field(alias="isResolved")
    replies: "SyncAssetTagsSyncAssetTagsAssetCommentsItemsReplies"


class SyncAssetTagsSyncAssetTagsAssetCommentsItemsMentionedUsers(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetCommentsItemsReplies(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class SyncAssetTagsSyncAssetTagsAssetCurrentUserPermissions(BaseModel):
    can_edit: bool = Field(alias="canEdit")
    can_delete: bool = Field(alias="canDelete")
    can_download: bool = Field(alias="canDownload")
    can_comment: bool = Field(alias="canComment")


class SyncAssetTagsSyncAssetTagsAssetCustomMetadata(BaseModel):
    typename__: Literal[
        "CustomMetadata", "CustomMetadataValue", "CustomMetadataValues"
    ] = Field(alias="__typename")
    property: "SyncAssetTagsSyncAssetTagsAssetCustomMetadataProperty"


class SyncAssetTagsSyncAssetTagsAssetCustomMetadataProperty(BaseModel):
    id: str
    creator: "SyncAssetTagsSyncAssetTagsAssetCustomMetadataPropertyCreator"
    created_at: Any = Field(alias="createdAt")
    modifier: Optional["SyncAssetTagsSyncAssetTagsAssetCustomMetadataPropertyModifier"]
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    name: str
    type: "SyncAssetTagsSyncAssetTagsAssetCustomMetadataPropertyType"
    help_text: Optional[str] = Field(alias="helpText")
    is_required: bool = Field(alias="isRequired")
    default_value: Optional[Any] = Field(alias="defaultValue")


class SyncAssetTagsSyncAssetTagsAssetCustomMetadataPropertyCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetCustomMetadataPropertyModifier(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetCustomMetadataPropertyType(BaseModel):
    typename__: Literal[
        "CustomMetadataPropertyType",
        "CustomMetadataPropertyTypeDate",
        "CustomMetadataPropertyTypeLongText",
        "CustomMetadataPropertyTypeMultiSelect",
        "CustomMetadataPropertyTypeNumber",
        "CustomMetadataPropertyTypeSelect",
        "CustomMetadataPropertyTypeText",
        "CustomMetadataPropertyTypeUrl",
    ] = Field(alias="__typename")
    name: str


class SyncAssetTagsSyncAssetTagsAssetWorkflowTask(BaseModel):
    id: str
    assigned_users: List[
        Optional["SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAssignedUsers"]
    ] = Field(alias="assignedUsers")
    asset: Optional["SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAsset"]
    title: Optional[str]
    description: Optional[str]
    status: "SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatus"
    checklist_item: "SyncAssetTagsSyncAssetTagsAssetWorkflowTaskChecklistItem" = Field(
        alias="checklistItem"
    )


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAssignedUsers(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAsset(BaseModel):
    typename__: Literal[
        "Asset", "Audio", "Document", "EmbeddedContent", "File", "Image", "Video"
    ] = Field(alias="__typename")
    id: str
    created_at: Any = Field(alias="createdAt")
    modified_at: Optional[Any] = Field(alias="modifiedAt")
    title: str
    description: Optional[str]
    external_id: Optional[str] = Field(alias="externalId")
    expires_at: Optional[Any] = Field(alias="expiresAt")
    status: AssetStatusType
    variants: Optional["SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAssetVariants"]
    preview_background_color: Optional[
        "SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAssetPreviewBackgroundColor"
    ] = Field(alias="previewBackgroundColor")


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAssetVariants(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAssetPreviewBackgroundColor(BaseModel):
    red: Any
    green: Any
    blue: Any
    alpha: Any


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatus(BaseModel):
    id: str
    name: str
    color: "SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusColor"
    assigned_users: List[
        Optional["SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusAssignedUsers"]
    ] = Field(alias="assignedUsers")
    checklist_presets: List[
        Optional["SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusChecklistPresets"]
    ] = Field(alias="checklistPresets")
    tasks: "SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusTasks"
    enter_rules: List[Optional[WorkflowStatusEnterRule]] = Field(alias="enterRules")


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusColor(BaseModel):
    red: Any
    green: Any
    blue: Any
    alpha: Any


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusAssignedUsers(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusChecklistPresets(BaseModel):
    id: str
    content: str


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatusTasks(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskChecklistItem(BaseModel):
    total: int
    page: int
    limit: int
    has_next_page: bool = Field(alias="hasNextPage")
    items: Optional[
        List[Optional["SyncAssetTagsSyncAssetTagsAssetWorkflowTaskChecklistItemItems"]]
    ]


class SyncAssetTagsSyncAssetTagsAssetWorkflowTaskChecklistItemItems(BaseModel):
    id: str
    content: str


SyncAssetTags.model_rebuild()
SyncAssetTagsSyncAssetTags.model_rebuild()
SyncAssetTagsSyncAssetTagsAsset.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetAttachments.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetRelatedAssets.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetRelatedAssetsItems.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetComments.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetCommentsItems.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetCustomMetadata.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetCustomMetadataProperty.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetWorkflowTask.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetWorkflowTaskAsset.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetWorkflowTaskStatus.model_rebuild()
SyncAssetTagsSyncAssetTagsAssetWorkflowTaskChecklistItem.model_rebuild()
