# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Any, Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class UninstallWebhook(BaseModel):
    uninstall_webhook: Optional["UninstallWebhookUninstallWebhook"] = Field(
        alias="uninstallWebhook"
    )


class UninstallWebhookUninstallWebhook(BaseModel):
    webhook: "UninstallWebhookUninstallWebhookWebhook"


class UninstallWebhookUninstallWebhookWebhook(BaseModel):
    typename__: Literal["ProjectWebhook", "Webhook"] = Field(alias="__typename")
    id: str
    creator: "UninstallWebhookUninstallWebhookWebhookCreator"
    created_at: Any = Field(alias="createdAt")
    name: str
    notification_url: Any = Field(alias="notificationUrl")
    secret: str


class UninstallWebhookUninstallWebhookWebhookCreator(BaseModel):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


UninstallWebhook.model_rebuild()
UninstallWebhookUninstallWebhook.model_rebuild()
UninstallWebhookUninstallWebhookWebhook.model_rebuild()
