# Generated by ariadne-codegen
# Source: queries-mutations

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateWorkflowChecklistPreset(BaseModel):
    update_workflow_checklist_preset: Optional[
        "UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPreset"
    ] = Field(alias="updateWorkflowChecklistPreset")


class UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPreset(BaseModel):
    checklist_preset: Optional[
        "UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPresetChecklistPreset"
    ] = Field(alias="checklistPreset")


class UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPresetChecklistPreset(
    BaseModel
):
    id: str
    content: str
    assigned_user: Optional[
        "UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPresetChecklistPresetAssignedUser"
    ] = Field(alias="assignedUser")


class UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPresetChecklistPresetAssignedUser(
    BaseModel
):
    typename__: Literal["AccountUser", "User"] = Field(alias="__typename")
    id: str
    name: Optional[str]


UpdateWorkflowChecklistPreset.model_rebuild()
UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPreset.model_rebuild()
UpdateWorkflowChecklistPresetUpdateWorkflowChecklistPresetChecklistPreset.model_rebuild()
